config/routes.rb
Rails.application.routes.draw do
  root "inventory_items#index"

  resources :inventory_items
  # resources :warehouses
  resources :warehouses do
    resources :locations, controller: 'warehouses/locations'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/inventory_item.rb
class InventoryItem < ApplicationRecord
  belongs_to :location
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :warehouse
  has_one :inventory_item
end

app/models/warehouse.rb
class Warehouse < ActiveRecord::Base
  has_many :location, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/inventory_items_controller.rb
class InventoryItemsController < ApplicationController
  before_action :set_inventory_item, only: %i[ show edit update destroy ]

  # GET /inventory_items or /inventory_items.json
  def index
    @inventory_items = InventoryItem.all
  end

  # GET /inventory_items/1 or /inventory_items/1.json
  def show
  end

  # GET /inventory_items/new
  def new
    @locations = Location.where(availability:true)
    @inventory_item = InventoryItem.new
  end

  # GET /inventory_items/1/edit
  def edit
  end

  # POST /inventory_items or /inventory_items.json
  def create
    @locations = Location.where(availability:true)
    @inventory_item = InventoryItem.create(inventory_item_params)
    @inventory_item.locations_id = params[:locations_id]
    respond_to do |format|
      if @inventory_item.save
        format.html { redirect_to inventory_items_url, notice: "Inventory item was successfully created." }
        format.json { render :show, status: :created, location: @inventory_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @inventory_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventory_items/1 or /inventory_items/1.json
  def update
    respond_to do |format|
      if @inventory_item.update(inventory_item_params)
        format.html { redirect_to inventory_item_url(@inventory_item), notice: "Inventory item was successfully updated." }
        format.json { render :show, status: :ok, location: @inventory_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @inventory_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventory_items/1 or /inventory_items/1.json
  def destroy
    @inventory_item.destroy

    respond_to do |format|
      format.html { redirect_to inventory_items_url, notice: "Inventory item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inventory_item
      @inventory_item = InventoryItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def inventory_item_params
      params.require(:inventory_item).permit(:name, :upc_code, :quantity, :category,
                                             :status, :date_of_arrival, :description, :locations_id)
    end
end

app/controllers/warehouses/locations_controller.rb
class Warehouses::LocationsController < ApplicationController
  before_action :set_location, only: %i[edit update destroy ]
  before_action :set_warehouse, only: %i[new edit update destroy index show]


  # GET /locations or /locations.json
  def index
    # @warehouse = Warehouse.where(warehouse_id: params[:warehouse_id])
    @locations = Location.where(warehouse_id: params[:warehouse_id])
  end

  # GET /locations/1 or /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    # @location = Location.create(
    #   location_params.merge(warehouse_id: @warehouse.id)
    # )
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations or /locations.json
  def create
    @location = Location.new(location_params)
    @warehouse = Warehouse.find(params[:warehouse_id])

    @location.warehouse_id = @warehouse.id
    respond_to do |format|
      if @location.save
        format.html { redirect_to warehouse_locations_url(@warehouse), notice: "Warehouse was successfully created." }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1 or /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to warehouse_locations_url(@warehouse), notice: "Warehouse was successfully updated." }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1 or /locations/1.json
  def destroy
    @location.destroy

    respond_to do |format|
      format.html { redirect_to warehouse_locations_url(@warehouse), notice: "Inventory item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_location
    @location = Location.find(params[:id])
  end

  def set_warehouse
    @warehouse = Warehouse.find(params[:warehouse_id])
  end

  # Only allow a list of trusted parameters through.
  def location_params
    params.require(:location).permit(:floor, :section, :rack, :number, :availability)
  end
end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController
  before_action :set_warehouse, only: %i[ show edit update destroy ]

  # GET /warehouses or /warehouses.json
  def index
    @warehouses = Warehouse.all
  end

  # GET /warehouses/1 or /warehouses/1.json
  def show
  end

  # GET /warehouses/new
  def new
    @warehouse = Warehouse.new
  end

  # GET /warehouses/1/edit
  def edit
  end

  # POST /warehouses or /warehouses.json
  def create
    @warehouse = Warehouse.new(warehouse_params)

    respond_to do |format|
      if @warehouse.save
        format.html { redirect_to warehouse_url(@warehouse), notice: "Inventory item was successfully created." }
        format.json { render :show, status: :created, location: @warehouse }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @warehouse.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /warehouses/1 or /warehouses/1.json
  def update
    respond_to do |format|
      if @warehouse.update(warehouse_params)
        format.html { redirect_to warehouse_url(@warehouse), notice: "Inventory item was successfully updated." }
        format.json { render :show, status: :ok, location: @warehouse }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @warehouse.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /warehouses/1 or /warehouses/1.json
  def destroy
    @warehouse.destroy

    respond_to do |format|
      format.html { redirect_to warehouses_url, notice: "Inventory item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_warehouse
    @warehouse = Warehouse.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def warehouse_params
    params.require(:warehouse).permit(:name, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inventory_items_helper.rb
module InventoryItemsHelper
end

app/views/inventory_items/_form.html.erb
<%= form_with(model: inventory_item) do |form| %>
  <% if inventory_item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(inventory_item.errors.count, "error") %> prohibited this inventory_item from being saved:</h2>

      <ul>
        <% inventory_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <% form.label :name %>
    <%= form.text_field :name, class:"form-control", placeholder:"Name" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :upc_code, class:"form-control", placeholder:"UPC" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :quantity, class:"form-control", placeholder:"Quantity" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :category, class:"form-control", placeholder:"Category" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :description, class:"form-control", placeholder:"Description" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :status, class:"form-control", placeholder:"Status" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :date_of_arrival, class:"form-control", placeholder:"Date of Arrival" %>
  </div>

  <div class="field form-group">
    <%= form.label :available_locations %>
    <%#= form.collection_select(:inventory_item, :locations_id, Location.all, :id, :number)%>
    <%= select(:inventory_items, "locations_id", @locations.collect{|l|[l.floor+'-'+l.section++'-' +l.rack+'-'+l.number.to_s, l.id]},include_blank:true )%>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/inventory_items/_inventory_item.html.erb
<div id="<%= dom_id inventory_item %>">
</div>

app/views/inventory_items/edit.html.erb
<h1>Editing inventory item</h1>

<%= render "form", inventory_item: @inventory_item %>

<br>

<div>
  <%= link_to "Show this inventory item", @inventory_item %> |
  <%= link_to "Back to inventory items", inventory_items_path %>
</div>

app/views/inventory_items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Inventory items</h1>

<table class="table table-striped table-bordered table-hover">
  <thead class="thead-dark">
  <tr>
    <th>Name</th>
    <th>UPC</th>
    <th>Quantity</th>
    <th>Category</th>
    <th>Status</th>
    <th>Date of arrival</th>
    <th>Description</th>
    <th>Location</th>

  </tr>
  </thead>

  <tbody>
  <% @inventory_items.each do |item| %>

      <tr>
        <td><%= item.name %></td>
        <td><%= item.upc_code %></td>
        <td><%= item.quantity %></td>
        <td><%= item.category %></td>
        <td><%= item.status %></td>
        <td><%= item.date_of_arrival %></td>
        <td><%= item.description %></td>
        <td><%= Warehouse.find(Location.find(item.locations_id).warehouse_id).name+'-'+Location.find(item.locations_id).floor+'-'+Location.find(item.locations_id).section++'-'
                +Location.find(item.locations_id).rack+'-'+Location.find(item.locations_id).number.to_s %></td>
        <td><%= link_to 'Edit', item, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %></td>
<!--        <td><%#= link_to 'Edit', item, method: :edit, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %></td>-->

      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New inventory item", new_inventory_item_path %>

app/views/inventory_items/new.html.erb
<h1>New inventory item</h1>

<%= render "form", inventory_item: @inventory_item %>

<br>

<div>
  <%= link_to "Back to inventory items", inventory_items_path %>
</div>

app/views/inventory_items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @inventory_item %>

<div>
  <%= link_to "Edit this inventory item", edit_inventory_item_path(@inventory_item) %> |
  <%= link_to "Back to inventory items", inventory_items_path %>

  <%= button_to "Destroy this inventory item", @inventory_item, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LogisticsManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/warehouses/_form.html.erb
<%= form_with(model: warehouse) do |form| %>
  <% if warehouse.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(warehouse.errors.count, "error") %> prohibited this warehouse from being saved:</h2>

      <ul>
        <% warehouse.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <% form.label :name %>
    <%= form.text_field :name, class:"form-control", placeholder:"Name" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :address, class:"form-control", placeholder:"Address" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/warehouses/_warehouse.html.erb
<div id="<%= dom_id warehouse %>">
</div>

app/views/warehouses/edit.html.erb
<h1>Editing the warehouse</h1>

<%= render "form", warehouse: @warehouse %>

<br>

<div>
  <%= link_to "Show this warehouse", @warehouse %> |
  <%= link_to "Back to warehouses", warehouses_path %>
</div>

app/views/warehouses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Warehouses</h1>

<table class="table table-striped table-bordered table-hover">
  <thead class="thead-dark">
  <tr>
    <th>Name</th>
    <th>Address</th>

  </tr>
  </thead>

  <tbody>
  <% @warehouses.each do |item| %>

      <tr>
        <td><%= item.name %></td>
        <td><%= item.address %></td>
        <td><%= link_to 'Edit', item, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New warehouse", new_warehouse_path %>

app/views/warehouses/locations/_form.html.erb
<%= form_with(model: [@warehouse, @location], local: true) do |form| %>
  <% if @location.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
        <% @location.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :floor, class:"form-control", placeholder:"Floor" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :section, class:"form-control", placeholder:"Section" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :rack, class:"form-control", placeholder:"Rack" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :number, class:"form-control", placeholder:"Number" %>
  </div>

  <div class="field form-group">
    <%= form.select(:availability, options_for_select([['Available', true], ['Not Available', false]]))%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/warehouses/locations/_location.html.erb
<div id="<%= dom_id location %>">
</div>

app/views/warehouses/locations/edit.html.erb
<h1>Editing the location</h1>

<%= render "form", model: @location %>

<br>

<div>
  <%= link_to "Show this location", warehouse_location_path(@warehouse, @location) %> |
  <%= link_to "Back to locations", warehouse_locations_path(@warehouse) %>
</div>

app/views/warehouses/locations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Locations</h1>

<table class="table table-striped table-bordered table-hover">
  <thead class="thead-dark">
  <tr>
    <th>Floor</th>
    <th>Section</th>
    <th>Rack</th>
    <th>Number</th>
    <th>Availability</th>
  </tr>
  </thead>

  <tbody>
  <% @locations.each do |item| %>

      <tr>
        <td><%= item.floor %></td>
        <td><%= item.section %></td>
        <td><%= item.rack %></td>
        <td><%= item.number %></td>
        <td><%= item.availability %></td>
        <td><%= link_to 'Edit', edit_warehouse_location_path(@warehouse, item), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New location", new_warehouse_location_path %>

app/views/warehouses/locations/new.html.erb
<h1>New Location</h1>

<%= render "form", location:@location %>

<br>

<div>
  <%= link_to "Back to locations", warehouse_locations_path %>
</div>

app/views/warehouses/locations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @location %>

<div>
  <%= link_to "Edit this location", edit_location_path(@location) %> |
  <%= link_to "Back to locations", warehouse_locations_path %>

  <%= button_to "Destroy this location", @location, method: :delete %>
</div>

app/views/warehouses/new.html.erb
<h1>New warehouse</h1>

<%= render "form", warehouse: @warehouse %>

<br>

<div>
  <%= link_to "Back to warehouses", warehouses_path %>
</div>

app/views/warehouses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @warehouse %>

<div>
  <%= link_to "Edit the basic info of the warehouse", edit_warehouse_path(@warehouse) %> |
  <%= link_to "Edit the storing spaces of the warehouse", warehouse_locations_url(@warehouse) %> |
  <%= link_to "Back to warehouses", warehouses_path %>

  <%= button_to "Destroy this warehouse", @warehouse, method: :delete %>
</div>